# Generated by Django 3.1.4 on 2021-01-11 16:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategories',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelManagers(
            name='productcategories',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
